AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS CloudFormation Template for KOZ API

###############################################################################
Parameters:
###############################################################################
  EnvironmentName:
    Description: Environment name for the application dev/staging/production
    Type: String
    AllowedValues:
      - bradlab
      - dev
      - preprod
      - prod
    Default: bradlab
###############################################################################
Resources:
###############################################################################
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "chatbot-dbtable-${EnvironmentName}"
      # Définition des attributs utilisés comme clés pour la table principale et les GSI
      AttributeDefinitions:
        - AttributeName: "chat_id"
          AttributeType: "S"
        - AttributeName: "timestamp"
          AttributeType: "S"
        - AttributeName: "user_id" # Attribut nécessaire pour UserIndex
          AttributeType: "S"
      # Schéma de la clé primaire de la table principale
      KeySchema:
        - AttributeName: "chat_id"
          KeyType: "HASH"
        - AttributeName: "timestamp"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      
      # --- Global Secondary Indexes (GSI) ---
      GlobalSecondaryIndexes:
        # GSI 1: UserIndex (pour les messages d'un utilisateur)
        - IndexName: "UserIndex"
          KeySchema:
            - AttributeName: "user_id"
              KeyType: "HASH"
            - AttributeName: "timestamp"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes: # Attributs à projeter en plus des clés de l'index et de la table
              - "chat_id"
              - "message_id"
              - "role"
              - "text"
              - "user_name"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "chatbot-lambda-${EnvironmentName}"
      CodeUri: ../
      Handler: src/main.handler
      Runtime: python3.12
      Environment:
        Variables:
          ENV_NAME: brad_test
          AWS_REGION_NAME: eu-west-3
          DYNAMO_TABLE: chatbot-dbtable-bradlab
          AWS_PROFILE: bradlab_profile
          TELEGRAM_BOT_TOKEN: 7916941219:AAGUKhpi9FHA-Iv-6PeGui9P_Bbq1uSC37c
          TELEGRAM_API_URL: https://api.telegram.org/bot
          # WEBHOOK_URL: !Sub ${TELEGRAM_API_URL}/setWebhook?url=https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/webhook
          # WEBHOOK_URL: !Sub "https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/webhook"
          WEBHOOK_URL: !Sub "https://p48s0cupm7.execute-api.eu-west-3.amazonaws.com/webhook"
          # Secrets injectés dynamiquement
          MISTRAL_API_KEY: w5pOu152w1ydl9m22ZGR9gnLAskQ4FwQ
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub "chatbot-apigateway-${EnvironmentName}"


Outputs:
  DynamoDBTableName:
    Value: !Ref DynamoDBTable
  ApiUrl:
    Description: URL of your API
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'