AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS CloudFormation Template for KOZ API

###############################################################################
Parameters:
###############################################################################
  EnvironmentName:
    Description: Environment name for the application dev/staging/production
    Type: String
    AllowedValues:
      - bradlab
      - dev
      - preprod
      - prod
    Default: bradlab
###############################################################################

  AWSRegionName:
    Description: AWS region where resources will be deployed (e.g. eu-west-3)
    Type: String
    Default: eu-west-3
  DynamoTable:
    Description: Name of the DynamoDB table used to persist chatbot conversations
    Type: String
    Default: ""
    NoEcho: true
  AwsProfile:
    Description: AWS CLI profile name used for deployment (for local/devops usage)
    Type: String
    Default: esgis_profile
  MistralApiKey:
    Description: API key for accessing the Mistral AI service
    Type: String
    Default: ""
    NoEcho: true
  TelegramBotToken:
    Description: Telegram bot token for authenticating with the Telegram API
    Type: String
    Default: ""
    NoEcho: true
  ApiWehookUrl:
    Type: String
    Default: ""
  TelegramApiBotUrl:
    Type: String
    Default: https://api.telegram.org/bot
###############################################################################
Resources:
###############################################################################
  DynamoDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "chatbot-dbtable-${EnvironmentName}"
      # Définition des attributs utilisés comme clés pour la table principale et les GSI
      AttributeDefinitions:
        - AttributeName: "chat_id"
          AttributeType: "S"
        - AttributeName: "timestamp"
          AttributeType: "S"
        - AttributeName: "user_id" # Attribut nécessaire pour UserIndex
          AttributeType: "S"
      # Schéma de la clé primaire de la table principale
      KeySchema:
        - AttributeName: "chat_id"
          KeyType: "HASH"
        - AttributeName: "timestamp"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      
      # --- Global Secondary Indexes (GSI) ---
      GlobalSecondaryIndexes:
        # GSI 1: UserIndex (pour les messages d'un utilisateur)
        - IndexName: "UserIndex"
          KeySchema:
            - AttributeName: "user_id"
              KeyType: "HASH"
            - AttributeName: "timestamp"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "INCLUDE"
            NonKeyAttributes: # Attributs à projeter en plus des clés de l'index et de la table
              - "chat_id"
              - "message_id"
              - "role"
              - "text"
              - "user_name"
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "chatbot-lambda-${EnvironmentName}"
      CodeUri: ../
      Handler: src/main.handler
      Runtime: python3.12
      Environment:
        Variables:
          ENV_NAME: !Ref EnvironmentName
          AWS_REGION_NAME: !Ref AWSRegionName
          DYNAMO_TABLE: !Ref DynamoDBTable
          MISTRAL_API_KEY: !Ref MistralApiKey
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          TELEGRAM_API_URL: !Ref TelegramApiBotUrl
          WEBHOOK_URL:  !Ref ApiWehookUrl
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - Statement:
            - Effect: Allow
              Action: "*"
              Resource: "*"
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api

  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub "chatbot-apigateway-${EnvironmentName}"


Outputs:
  DynamoDBTableName:
    Value: !Ref DynamoDBTable
  ApiUrl:
    Description: URL of our API
    Value:
      Fn::Sub: 'https://${Api}.execute-api.${AWS::Region}.${AWS::URLSuffix}/'
